In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import os
PATH = os.getcwd()

In [3]:
DATA_PATH = os.path.join(PATH, 'images_data')
data_dir_list = os.listdir(DATA_PATH)

In [4]:
print(data_dir_list)

['Cats', 'Dogs', 'Horses', 'Humans']


In [5]:
img_rows=224
img_cols=224
num_channel=3

num_epoch=10
batch_size=32

img_data_list=[]
classes_names_list=[]

In [6]:
import cv2

for dataset in data_dir_list:
    classes_names_list.append(dataset) 
    print ('Loading images from {} folder\n'.format(dataset)) 
    img_list=os.listdir(DATA_PATH+'/'+ dataset)
    for img in img_list:
        input_img=cv2.imread(DATA_PATH + '/'+ dataset + '/'+ img )
        input_img_resize=cv2.resize(input_img,(img_rows, img_cols))
        img_data_list.append(input_img_resize)

Loading images from Cats folder

Loading images from Dogs folder

Loading images from Horses folder

Loading images from Humans folder



In [7]:
num_classes = len(classes_names_list)
print(num_classes)

4


In [8]:
import numpy as np

img_data = np.array(img_data_list)
img_data = img_data.astype('float32')
img_data /= 255

In [9]:
print (img_data.shape)

(808, 224, 224, 3)


In [10]:
num_of_samples = img_data.shape[0]
input_shape = img_data[0].shape

In [11]:
classes = np.ones((num_of_samples,), dtype='int64')

classes[0:202]=0
classes[202:404]=1
classes[404:606]=2
classes[606:]=3

In [12]:
from keras.utils import to_categorical

classes = to_categorical(classes, num_classes)

Using TensorFlow backend.


In [13]:
from sklearn.utils import shuffle

X, Y = shuffle(img_data, classes, random_state=2)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [15]:
y_test.shape

(162, 4)

In [16]:
y_train.shape

(646, 4)

In [25]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras import optimizers

In [92]:
model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=input_shape))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [93]:
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=["accuracy"])

In [94]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_32 (Conv2D)           (None, 222, 222, 32)      896       
_________________________________________________________________
conv2d_33 (Conv2D)           (None, 220, 220, 32)      9248      
_________________________________________________________________
max_pooling2d_20 (MaxPooling (None, 110, 110, 32)      0         
_________________________________________________________________
dropout_18 (Dropout)         (None, 110, 110, 32)      0         
_________________________________________________________________
conv2d_34 (Conv2D)           (None, 108, 108, 64)      18496     
_________________________________________________________________
conv2d_35 (Conv2D)           (None, 106, 106, 64)      36928     
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 53, 53, 64)      

In [95]:
model.layers

In [96]:
model.weights

[<tf.Variable 'conv2d_32/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
 array([[[[ 0.07678224,  0.09463818, -0.12440526,  0.11993076,
            0.13325201,  0.1008423 ,  0.11898859,  0.00636776,
            0.04068914, -0.02384677,  0.01979248,  0.05982994,
           -0.02069925,  0.09641643,  0.02204329,  0.08712244,
           -0.02213232,  0.118082  , -0.02963553,  0.06735153,
           -0.01118872, -0.08326   ,  0.00621304, -0.12266005,
           -0.08321426,  0.0273613 , -0.03178767, -0.09314308,
            0.08756451,  0.13676934, -0.02963822, -0.08688299],
          [ 0.02434   , -0.13766342, -0.02652779, -0.09675057,
           -0.08460203, -0.11057214, -0.08729921,  0.03984269,
           -0.12685484, -0.05976643, -0.08632496, -0.01598549,
            0.06277286, -0.01991108, -0.01512282, -0.08341686,
            0.02651992,  0.08315016, -0.01190893, -0.05064309,
           -0.00458997, -0.10463008, -0.06552032, -0.00512192,
           -0.09466967,  0.01916309, -0.

In [97]:
model.layers[0].get_weights()

[array([[[[ 0.07678224,  0.09463818, -0.12440526,  0.11993076,
            0.13325201,  0.1008423 ,  0.11898859,  0.00636776,
            0.04068914, -0.02384677,  0.01979248,  0.05982994,
           -0.02069925,  0.09641643,  0.02204329,  0.08712244,
           -0.02213232,  0.118082  , -0.02963553,  0.06735153,
           -0.01118872, -0.08326   ,  0.00621304, -0.12266005,
           -0.08321426,  0.0273613 , -0.03178767, -0.09314308,
            0.08756451,  0.13676934, -0.02963822, -0.08688299],
          [ 0.02434   , -0.13766342, -0.02652779, -0.09675057,
           -0.08460203, -0.11057214, -0.08729921,  0.03984269,
           -0.12685484, -0.05976643, -0.08632496, -0.01598549,
            0.06277286, -0.01991108, -0.01512282, -0.08341686,
            0.02651992,  0.08315016, -0.01190893, -0.05064309,
           -0.00458997, -0.10463008, -0.06552032, -0.00512192,
           -0.09466967,  0.01916309, -0.11988015, -0.06785376,
            0.04645592,  0.04443184, -0.04142933, -0.0

In [98]:
hist = model.fit(X_train, y_train, batch_size=batch_size, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

Train on 646 samples, validate on 162 samples
Epoch 1/10
646/646 [==============================] - 110s 170ms/step - loss: 2.7722 - accuracy: 0.2415 - val_loss: 1.3848 - val_accuracy: 0.3580
Epoch 2/10
646/646 [==============================] - 116s 180ms/step - loss: 1.3761 - accuracy: 0.3266 - val_loss: 1.3760 - val_accuracy: 0.3827
Epoch 3/10
646/646 [==============================] - 117s 180ms/step - loss: 1.3358 - accuracy: 0.3483 - val_loss: 1.3546 - val_accuracy: 0.3457
Epoch 4/10
646/646 [==============================] - 118s 183ms/step - loss: 1.4156 - accuracy: 0.3839 - val_loss: 1.3508 - val_accuracy: 0.3272
Epoch 5/10
646/646 [==============================] - 89s 137ms/step - loss: 1.2789 - accuracy: 0.4334 - val_loss: 1.2619 - val_accuracy: 0.4568
Epoch 6/10
646/646 [==============================] - 75s 116ms/step - loss: 1.1643 - accuracy: 0.4892 - val_loss: 1.7734 - val_accuracy: 0.2654
Epoch 7/10
646/646 [==============================] - 77s 120ms/step - loss: 1.1

In [99]:
score = model.evaluate(X_test, y_test, batch_size=batch_size)

print('Test Loss:', score[0])
print('Test Accuracy:', score[1])

162/162 [==============================] - 4s 22ms/step
Test Loss: 1.8065856430265639
Test Accuracy: 0.48765432834625244


## Here we have the probabilties of 4 classes in the output layer

In [100]:
from sklearn.metrics import confusion_matrix

Y_pred = model.predict(X_test)
print(Y_pred)

[[4.11088949e-05 5.47355860e-02 9.45179641e-01 4.36867158e-05]
 [5.95648191e-04 4.38391864e-02 9.55432892e-01 1.32275789e-04]
 [1.42817244e-01 7.45351553e-01 9.39243734e-02 1.79068875e-02]
 [4.17812914e-01 5.69570899e-01 1.18788434e-02 7.37281574e-04]
 [1.75324923e-04 9.59588885e-01 3.55878957e-02 4.64782398e-03]
 [1.29060773e-02 4.50141102e-01 3.97319913e-01 1.39632851e-01]
 [1.01003304e-01 5.39184749e-01 1.43097118e-01 2.16714755e-01]
 [2.17148531e-02 8.78250420e-01 8.96961465e-02 1.03385728e-02]
 [1.98626440e-05 9.99979854e-01 6.93633737e-08 1.21929503e-07]
 [1.61362323e-03 7.88096339e-02 1.00048646e-01 8.19528103e-01]
 [1.06844679e-02 6.83375657e-01 3.01818341e-01 4.12143767e-03]
 [2.16934022e-05 4.71542851e-04 1.15864706e-04 9.99390841e-01]
 [5.17231598e-03 3.36894467e-02 9.52548325e-01 8.58996157e-03]
 [1.63296505e-03 3.97308208e-02 2.11850367e-03 9.56517756e-01]
 [8.19062255e-03 4.04059082e-01 5.78856766e-01 8.89354572e-03]
 [1.45525817e-04 3.29335295e-02 9.66689408e-01 2.315530

## Class with the high probablity in the output layer is label given by the neural network

In [101]:
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

[2 2 1 1 1 1 1 1 1 3 1 3 2 3 2 2 1 1 3 3 3 3 1 1 1 1 1 3 1 3 1 2 2 2 1 3 3
 2 3 2 2 1 2 1 1 1 2 1 2 1 2 3 1 1 2 2 1 2 1 1 3 2 3 3 3 1 3 2 1 2 2 1 1 2
 2 1 1 3 1 3 3 2 3 2 2 1 1 2 2 0 2 1 1 1 3 1 2 1 2 3 1 3 1 2 3 2 0 2 2 2 1
 3 2 1 1 1 3 2 3 3 1 2 3 1 2 1 1 2 1 0 2 3 1 1 3 3 3 2 3 1 1 3 3 1 3 2 1 1
 3 1 2 2 1 3 3 1 3 3 1 2 1 1]


In [102]:
print(confusion_matrix(np.argmax(y_test, axis=1), y_pred))

[[ 3 31  4  3]
 [ 0 19 11 10]
 [ 0  5 27  1]
 [ 0 12  6 30]]


### saving model

In [103]:
from keras.models import load_model

## saving the weights and layer configuration of the neural net

In [104]:
model.save('model.hdf5')

# Image agumentation ,creating image data generator

In [36]:
from keras.preprocessing.image import ImageDataGenerator

train_data_gen = ImageDataGenerator(
    rotation_range=20, #rotation ranges b/w 0 to 20
    shear_range=0.5, 
    zoom_range=0.4, 
    vertical_flip=True, 
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True) 

## Here we are not applying any agumentation on the test data as the model robustness should be maximized during the training phase

In [37]:
test_data_gen = ImageDataGenerator()

## saving the images which are agumented by the image generator

In [ ]:
TRN_AUGMENTED = os.path.join(PATH , 'Train_Augmented_Images')
TST_AUGMENTED = os.path.join(PATH , 'Test_Augmented_Images')

## *FLOW* ......Takes data & label arrays, generates batches of augmented data.

In [38]:
ftrain_generator = train_data_gen.flow(
        X_train,
        y_train,
        batch_size=batch_size, 
        shuffle=True)

In [39]:
ftest_generator = test_data_gen.flow(
        X_test,
        y_test,
        batch_size=batch_size, 
        shuffle=True)

## fitting the agumented images and evaluating the accuracy

In [ ]:
model.fit_generator(ftrain_generator, epochs = num_epoch, validation_data=ftest_generator,validation_steps=25,steps_per_epoch=X_train.shape[0]/batch_size)

In [ ]:
Y_pred = model.predict(X_test)
print(Y_pred)

In [ ]:
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

In [ ]:
print(confusion_matrix(np.argmax(y_test, axis=1), y_pred))


In [ ]:
f_model_evaluate = model.evaluate_generator(ftest_generator, verbose=1, steps=X_test.shape[0]/batch_size)

In [ ]:
f_model_evaluate

In [ ]:
f_model_predict = model.predict_generator(ftest_generator, verbose=1,steps=X_test.shape[0]/batch_size)

In [ ]:
f_model_predict.argmax(axis=-1)

# Trasfer learning--VGG16

### To build top on top of the VGG16 we use functional  API

In [26]:
from keras.layers import Input, Dense

In [27]:
image_input = Input(shape=(img_rows, img_cols, num_channel))

## loading the VGG with imagenet weights

In [28]:
from keras.applications.vgg16 import VGG16

model = VGG16(input_tensor=image_input, include_top=True, weights='imagenet')

 include_top: whether to include the 3 fully-connected layers at the top of the network.

weights: one of None (random initialization) or 'imagenet' (pre-training on ImageNet).

input_tensor: optional Keras tensor (i.e. output of layers.Input()) to use as image input for the model.


In [29]:
model.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [30]:
last_layer = model.get_layer('fc2').output
out = Dense(num_classes, activation='softmax', name='output')(last_layer)

In [31]:
from keras.models import Model

custom_vgg_model = Model(image_input, out)
custom_vgg_model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0   

In [32]:
for layer in custom_vgg_model.layers[:-1]:
    layer.trainable = False

In [33]:
custom_vgg_model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [34]:
Num_epoch=9

## Model VGG.fit

In [40]:
custom_vgg_model.fit_generator(ftrain_generator, epochs = Num_epoch, validation_data=ftest_generator,validation_steps=25,steps_per_epoch=X_train.shape[0]/batch_size)

Epoch 1/9
21/20 [===============================] - 217s 10s/step - loss: 2.0819 - accuracy: 0.3220 - val_loss: 1.1707 - val_accuracy: 0.4044
Epoch 2/9
21/20 [===============================] - 229s 11s/step - loss: 1.3716 - accuracy: 0.4040 - val_loss: 0.9781 - val_accuracy: 0.6118
Epoch 3/9
21/20 [===============================] - 222s 11s/step - loss: 1.2289 - accuracy: 0.4783 - val_loss: 0.7065 - val_accuracy: 0.6926
Epoch 4/9
21/20 [===============================] - 222s 11s/step - loss: 1.1563 - accuracy: 0.5279 - val_loss: 1.1629 - val_accuracy: 0.6368
Epoch 5/9
21/20 [===============================] - 233s 11s/step - loss: 1.1681 - accuracy: 0.5093 - val_loss: 0.9872 - val_accuracy: 0.6176
Epoch 6/9
21/20 [===============================] - 222s 11s/step - loss: 1.0351 - accuracy: 0.5681 - val_loss: 0.4208 - val_accuracy: 0.8031
Epoch 7/9
21/20 [===============================] - 230s 11s/step - loss: 1.1012 - accuracy: 0.5604 - val_loss: 0.4600 - val_accuracy: 0.6941
Epoch 

In [41]:
Y_pred_VGG = custom_vgg_model.predict(X_test)
print(Y_pred_VGG)

[[1.69285428e-04 5.76884905e-03 9.94008303e-01 5.35621548e-05]
 [9.16368049e-03 3.68106253e-02 9.51664209e-01 2.36153742e-03]
 [6.36741221e-02 7.43850052e-01 1.91626221e-01 8.49681208e-04]
 [2.53977120e-01 5.14868796e-01 2.20723346e-01 1.04307020e-02]
 [4.35439823e-03 6.58937693e-01 2.41861656e-01 9.48462635e-02]
 [7.92937633e-03 2.78308950e-02 9.58698273e-01 5.54152858e-03]
 [2.54746061e-03 9.55969915e-02 6.92997873e-01 2.08857715e-01]
 [3.26014496e-03 6.13350511e-01 8.14935565e-02 3.01895797e-01]
 [1.52806975e-02 9.45649266e-01 3.60467657e-02 3.02327774e-03]
 [5.50722843e-03 3.00024241e-01 6.07671082e-01 8.67974162e-02]
 [8.45628511e-03 9.35764372e-01 4.50397730e-02 1.07395751e-02]
 [1.79466943e-03 3.35684009e-02 8.81109852e-03 9.55825746e-01]
 [2.80715851e-03 1.97642446e-01 7.99285591e-01 2.64756556e-04]
 [2.35087820e-03 5.37705608e-02 1.76382557e-01 7.67496049e-01]
 [2.07872479e-03 1.11850649e-01 1.44399285e-01 7.41671324e-01]
 [5.59805194e-04 2.88881604e-02 9.69869375e-01 6.826457

In [42]:
y_pred_vgg = np.argmax(Y_pred_VGG, axis=1)
print(y_pred_vgg)

[2 2 1 1 1 2 2 1 1 2 1 3 2 3 3 2 1 3 3 2 1 3 1 0 0 1 3 3 1 3 2 1 2 2 2 3 2
 1 3 2 1 1 1 1 1 1 2 0 2 0 2 3 1 1 2 2 1 2 3 1 3 1 1 3 1 1 1 2 3 2 1 1 2 1
 3 0 1 3 1 2 1 1 1 2 2 1 2 3 1 2 2 1 1 0 3 1 2 2 2 3 1 2 1 1 1 3 1 3 2 2 2
 3 2 1 2 2 3 2 3 2 2 1 2 1 2 2 1 2 1 1 2 3 1 1 1 1 1 2 1 3 1 0 2 2 1 1 1 3
 3 1 1 2 1 3 3 3 3 1 1 2 1 1]


In [44]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(np.argmax(y_test, axis=1), y_pred_vgg))

[[ 7 31  3  0]
 [ 0 33  7  0]
 [ 0  1 32  0]
 [ 0  4 10 34]]


In [45]:
vgg_model_evaluate = custom_vgg_model.evaluate_generator(ftest_generator, verbose=1, steps=X_test.shape[0]/batch_size)

6/5 [===================================] - 25s 4s/step


In [46]:
vgg_model_evaluate

[0.6498516798019409, 0.654321014881134]

In [47]:
VGG_model_predict = custom_vgg_model.predict_generator(ftest_generator, verbose=1,steps=X_test.shape[0]/batch_size)

6/5 [===================================] - 24s 4s/step


In [48]:
VGG_model_predict.argmax(axis=-1)

array([2, 1, 1, 2, 1, 3, 2, 2, 1, 1, 3, 1, 1, 1, 3, 2, 2, 1, 3, 1, 1, 3,
       1, 1, 2, 2, 1, 3, 3, 2, 1, 1, 1, 2, 1, 2, 3, 2, 2, 3, 1, 3, 1, 1,
       1, 3, 2, 1, 2, 3, 1, 2, 2, 1, 1, 1, 1, 0, 3, 1, 2, 2, 2, 2, 1, 1,
       0, 1, 2, 2, 3, 1, 1, 3, 1, 1, 1, 1, 2, 2, 1, 2, 0, 2, 2, 0, 2, 0,
       3, 2, 3, 2, 3, 3, 3, 2, 1, 1, 3, 1, 1, 3, 2, 2, 1, 2, 1, 1, 1, 2,
       2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1,
       3, 2, 3, 3, 1, 0, 2, 3, 1, 1, 1, 3, 3, 3, 2, 3, 0, 3, 2, 1, 1, 2,
       3, 1, 3, 1, 1, 2, 1, 3], dtype=int64)

# Transfer learning--- ResNet50  

In [49]:
from keras.layers import Input
from keras.layers import Dense, GlobalAveragePooling2D
from keras.models import Model
from keras.optimizers import SGD

In [50]:
image_input = Input(shape=(img_rows, img_cols, num_channel))

In [51]:
from keras.applications.resnet50 import ResNet50
base_model = ResNet50(include_top=False, weights='imagenet',input_tensor=image_input,)

## Freezing the low layers and enhancing the model with top level layers

In [52]:
# Taking the output of the last convolution block in ResNet50
x = base_model.output

In [53]:
# Adding a Global Average Pooling layer
x = GlobalAveragePooling2D()(x)

In [54]:
# Adding a fully connected layer having 1024 neurons
x = Dense(1024, activation='relu')(x)

In [55]:
# Adding a fully connected layer having 4 neurons which will
# give the probability of image having either dog or cat or human or horse
predictions = Dense(4, activation='softmax')(x)

In [56]:
# Model to be trained
model = Model(inputs=base_model.input, outputs=predictions)

In [57]:
# We will try to train the last stage of ResNet50
for layer in base_model.layers[0:143]:
  layer.trainable = False
 
for layer in base_model.layers[143:]:
  layer.trainable = True

In [58]:
model.compile(optimizer=SGD(lr=0.0001, momentum=0.9), loss='categorical_crossentropy', metrics = ['accuracy'])

## Fitting data using ResNet50

In [59]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

Train on 646 samples, validate on 162 samples
Epoch 1/10
646/646 [==============================] - 216s 334ms/step - loss: 1.3583 - accuracy: 0.3282 - val_loss: 1.9071 - val_accuracy: 0.2037
Epoch 2/10
646/646 [==============================] - 216s 334ms/step - loss: 0.9360 - accuracy: 0.6950 - val_loss: 1.9025 - val_accuracy: 0.2037
Epoch 3/10
646/646 [==============================] - 220s 341ms/step - loss: 0.6411 - accuracy: 0.8638 - val_loss: 1.9114 - val_accuracy: 0.2037
Epoch 4/10
646/646 [==============================] - 219s 339ms/step - loss: 0.4804 - accuracy: 0.9226 - val_loss: 1.9074 - val_accuracy: 0.2037
Epoch 5/10
646/646 [==============================] - 213s 329ms/step - loss: 0.3748 - accuracy: 0.9427 - val_loss: 1.8799 - val_accuracy: 0.2037
Epoch 6/10
646/646 [==============================] - 221s 343ms/step - loss: 0.3082 - accuracy: 0.9567 - val_loss: 1.8756 - val_accuracy: 0.2037
Epoch 7/10
646/646 [==============================] - 224s 347ms/step - loss: 

In [60]:
Y_pred_resnet50 = custom_vgg_model.predict(X_test)
print(Y_pred_resnet50)

[[1.69285428e-04 5.76884905e-03 9.94008303e-01 5.35621548e-05]
 [9.16368049e-03 3.68106253e-02 9.51664209e-01 2.36153742e-03]
 [6.36741221e-02 7.43850052e-01 1.91626221e-01 8.49681208e-04]
 [2.53977120e-01 5.14868796e-01 2.20723346e-01 1.04307020e-02]
 [4.35439823e-03 6.58937693e-01 2.41861656e-01 9.48462635e-02]
 [7.92937633e-03 2.78308950e-02 9.58698273e-01 5.54152858e-03]
 [2.54746061e-03 9.55969915e-02 6.92997873e-01 2.08857715e-01]
 [3.26014496e-03 6.13350511e-01 8.14935565e-02 3.01895797e-01]
 [1.52806975e-02 9.45649266e-01 3.60467657e-02 3.02327774e-03]
 [5.50722843e-03 3.00024241e-01 6.07671082e-01 8.67974162e-02]
 [8.45628511e-03 9.35764372e-01 4.50397730e-02 1.07395751e-02]
 [1.79466943e-03 3.35684009e-02 8.81109852e-03 9.55825746e-01]
 [2.80715851e-03 1.97642446e-01 7.99285591e-01 2.64756556e-04]
 [2.35087820e-03 5.37705608e-02 1.76382557e-01 7.67496049e-01]
 [2.07872479e-03 1.11850649e-01 1.44399285e-01 7.41671324e-01]
 [5.59805194e-04 2.88881604e-02 9.69869375e-01 6.826457

In [61]:
Y_pred_resnet50 = np.argmax(Y_pred_VGG, axis=1)
print(Y_pred_resnet50)

[2 2 1 1 1 2 2 1 1 2 1 3 2 3 3 2 1 3 3 2 1 3 1 0 0 1 3 3 1 3 2 1 2 2 2 3 2
 1 3 2 1 1 1 1 1 1 2 0 2 0 2 3 1 1 2 2 1 2 3 1 3 1 1 3 1 1 1 2 3 2 1 1 2 1
 3 0 1 3 1 2 1 1 1 2 2 1 2 3 1 2 2 1 1 0 3 1 2 2 2 3 1 2 1 1 1 3 1 3 2 2 2
 3 2 1 2 2 3 2 3 2 2 1 2 1 2 2 1 2 1 1 2 3 1 1 1 1 1 2 1 3 1 0 2 2 1 1 1 3
 3 1 1 2 1 3 3 3 3 1 1 2 1 1]


In [62]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(np.argmax(y_test, axis=1), Y_pred_resnet50))

[[ 7 31  3  0]
 [ 0 33  7  0]
 [ 0  1 32  0]
 [ 0  4 10 34]]


## here my resnet50 has vanishing gradient where the low layers of the network have not learnt the weights properly ,hence it caused me a saturated validation accuracy

In [63]:
score = model.evaluate(X_test, y_test, batch_size=batch_size)

print('Test Loss:', score[0])
print('Test Accuracy:', score[1])

162/162 [==============================] - 37s 230ms/step
Test Loss: 1.8777658026895405
Test Accuracy: 0.20370370149612427


# Trasnfer learning--AlexNet architecture

In [76]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten,Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras import optimizers

In [ ]:
model = Sequential()

# 1st Convolutional Layer
model.add(Conv2D(filters=96, input_shape=(224,224,3), kernel_size=(11,11),strides=(4,4), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
# Batch Normalisation before passing it to the next layer
model.add(BatchNormalization())

# 2nd Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(11,11), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
model.add(BatchNormalization())

#3
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(BatchNormalization())

#4
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(BatchNormalization())

# 5th Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
model.add(BatchNormalization())

# Passing it to a dense layer
model.add(Flatten())
# 1st Dense Layer
model.add(Dense(4096, input_shape=(224*224*3,)))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

# 2nd Dense Layer
model.add(Dense(4096))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

# 3rd Dense Layer
model.add(Dense(1000))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

# Output Layer
model.add(Dense(num_classes, activation='softmax'))




In [83]:
model = Sequential()

# 1st Convolutional Layer
model.add(Conv2D(filters=96, input_shape=(224,224,3), kernel_size=(11,11),strides=(4,4), padding='valid',kernel_initializer='normal'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
# Batch Normalisation before passing it to the next layer
model.add(BatchNormalization())

# 2nd Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(11,11), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
model.add(BatchNormalization())

#3
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(BatchNormalization())

#4
model.add(Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(BatchNormalization())

# 5th Convolutional Layer
model.add(Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), padding='valid'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2), padding='valid'))
model.add(BatchNormalization())

# Passing it to a dense layer
model.add(Flatten())
# 1st Dense Layer
model.add(Dense(4096, input_shape=(224*224*3,)))
model.add(Activation('relu'))
#model.add(Dropout(0.2))
model.add(BatchNormalization())

# 2nd Dense Layer
model.add(Dense(4096))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

# 3rd Dense Layer
model.add(Dense(1000))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

# Output Layer
model.add(Dense(num_classes, activation='softmax'))




In [84]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 54, 54, 96)        34944     
_________________________________________________________________
activation_84 (Activation)   (None, 54, 54, 96)        0         
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 27, 27, 96)        0         
_________________________________________________________________
batch_normalization_36 (Batc (None, 27, 27, 96)        384       
_________________________________________________________________
conv2d_28 (Conv2D)           (None, 17, 17, 256)       2973952   
_________________________________________________________________
activation_85 (Activation)   (None, 17, 17, 256)       0         
_________________________________________________________________
max_pooling2d_18 (MaxPooling (None, 8, 8, 256)        

In [85]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

## Training the AlexNet on the agumented data

In [86]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

Train on 646 samples, validate on 162 samples
Epoch 1/10
646/646 [==============================] - 48s 75ms/step - loss: 3.2571 - accuracy: 0.3777 - val_loss: 181.8861 - val_accuracy: 0.2963
Epoch 2/10
646/646 [==============================] - 45s 69ms/step - loss: 1.3521 - accuracy: 0.4768 - val_loss: 19.4399 - val_accuracy: 0.2160
Epoch 3/10
646/646 [==============================] - 44s 68ms/step - loss: 1.1359 - accuracy: 0.5464 - val_loss: 4.1014 - val_accuracy: 0.3086
Epoch 4/10
646/646 [==============================] - 45s 70ms/step - loss: 1.2971 - accuracy: 0.5093 - val_loss: 6.2348 - val_accuracy: 0.2222
Epoch 5/10
646/646 [==============================] - 44s 68ms/step - loss: 1.0998 - accuracy: 0.5882 - val_loss: 3.9533 - val_accuracy: 0.3333
Epoch 6/10
646/646 [==============================] - 44s 69ms/step - loss: 1.0405 - accuracy: 0.6084 - val_loss: 1.9602 - val_accuracy: 0.3889
Epoch 7/10
646/646 [==============================] - 44s 68ms/step - loss: 1.0227 - ac

In [87]:
Y_pred_alex = custom_vgg_model.predict(X_test)
print(Y_pred_alex)

[[1.69285428e-04 5.76884905e-03 9.94008303e-01 5.35621548e-05]
 [9.16368049e-03 3.68106253e-02 9.51664209e-01 2.36153742e-03]
 [6.36741221e-02 7.43850052e-01 1.91626221e-01 8.49681208e-04]
 [2.53977120e-01 5.14868796e-01 2.20723346e-01 1.04307020e-02]
 [4.35439823e-03 6.58937693e-01 2.41861656e-01 9.48462635e-02]
 [7.92937633e-03 2.78308950e-02 9.58698273e-01 5.54152858e-03]
 [2.54746061e-03 9.55969915e-02 6.92997873e-01 2.08857715e-01]
 [3.26014496e-03 6.13350511e-01 8.14935565e-02 3.01895797e-01]
 [1.52806975e-02 9.45649266e-01 3.60467657e-02 3.02327774e-03]
 [5.50722843e-03 3.00024241e-01 6.07671082e-01 8.67974162e-02]
 [8.45628511e-03 9.35764372e-01 4.50397730e-02 1.07395751e-02]
 [1.79466943e-03 3.35684009e-02 8.81109852e-03 9.55825746e-01]
 [2.80715851e-03 1.97642446e-01 7.99285591e-01 2.64756556e-04]
 [2.35087820e-03 5.37705608e-02 1.76382557e-01 7.67496049e-01]
 [2.07872479e-03 1.11850649e-01 1.44399285e-01 7.41671324e-01]
 [5.59805194e-04 2.88881604e-02 9.69869375e-01 6.826457

In [88]:
Y_pred_alex = np.argmax(Y_pred_alex, axis=1)
print(Y_pred_alex)

[2 2 1 1 1 2 2 1 1 2 1 3 2 3 3 2 1 3 3 2 1 3 1 0 0 1 3 3 1 3 2 1 2 2 2 3 2
 1 3 2 1 1 1 1 1 1 2 0 2 0 2 3 1 1 2 2 1 2 3 1 3 1 1 3 1 1 1 2 3 2 1 1 2 1
 3 0 1 3 1 2 1 1 1 2 2 1 2 3 1 2 2 1 1 0 3 1 2 2 2 3 1 2 1 1 1 3 1 3 2 2 2
 3 2 1 2 2 3 2 3 2 2 1 2 1 2 2 1 2 1 1 2 3 1 1 1 1 1 2 1 3 1 0 2 2 1 1 1 3
 3 1 1 2 1 3 3 3 3 1 1 2 1 1]


In [89]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(np.argmax(y_test, axis=1), Y_pred_alex))

[[ 7 31  3  0]
 [ 0 33  7  0]
 [ 0  1 32  0]
 [ 0  4 10 34]]


In [90]:
alexnet_model_evaluate = model.evaluate_generator(ftest_generator, verbose=1, steps=X_test.shape[0]/batch_size)

6/5 [===================================] - 3s 575ms/step


In [91]:
alexnet_model_evaluate

[0.40158894658088684, 0.4135802388191223]

# VGG has been the best model for this data than Resnet50 and Alexnet